fragment taskFields on Task {
    _id
    title
    description
    priority
    dueDate
    dueTime
    duration
    segmentDuration
    resetMode
    resetTime
    progress
    state
    color
    isRecurring
    createdAt
    completedAt
}

fragment userFields on User {
    _id
    username
    name
    email
}

fragment taskProgressFields on Task {
    _id
    progress
    duration
    state
    completedAt
}

fragment taskEventFields on TaskEvent {
    title
    timestamp
    color
}


query GetTasks {
    tasks {
        ...taskFields
    }
}

query GetTaskEvents {
    taskEvents {
        ...taskEventFields
    }
}

query GetCurrentUserProfile {
    user_profile {
        ...userFields
    }
}

subscription UpdateTasks {
    updateTasks {
        ...taskProgressFields
    }
}

subscription EventLog {
    eventLog {
        ...taskEventFields
    }
}


mutation NewTask($input: TaskInput) {
    createTask(input: $input) {
        ...taskFields
    }
}

mutation SaveTask($input: TaskInput) {
    saveTask(input: $input) {
        ...taskFields
    }
}


mutation CompleteTask($id: String!) {
    completeTask(id: $id) {
        ...taskProgressFields
    }
}

mutation UncompleteTask($id: String!) {
    uncompleteTask(id: $id) {
        ...taskProgressFields
    }
}

mutation AddProgress($id: String!, $time: Int!) {
    addProgress(id: $id, time: $time) {
        ...taskProgressFields
    }
}